### ISSUE TITLE
Icon order changed again in Patch 10.1.5 (Fractures In Time)

### ISSUE THREAD

**Issue by Voxxel** [Shushuda/Mappy-Continued#10]
Hi there,

I hope you have recovered and you're well for now, Shushuda. 

Just wanted to report that the latest minor patch 10.1.5 brought some new minimap icons and it scrambled the blip map once again. I see a new type of exclamation / question mark with pink background maybe that mixed up the order. Would you take a look if you have some time, please. 
Thank you and good health to you!

**Comment by Shushuda** [comment]
Hello!

Sadly, I'm not recovered. I'm actually even worse than I was. I'm on a break from WoW because of that.

Thanks for the report! I will fix this soon, maybe this weekend. I won't test it, but it's just a texture, so it should be fine.

Thank you for the good wishes!

**Comment by Voxxel** [comment]
How could this be you're even worse, Weronika? Are you still in the hospital for a half year?
I thought medical treatment is above World average in Germany. You're in Germany afaik, or you live in Austria? Österreich is even better I heard of. If you'd live here in Hungary it would be normal to circulating in the health care system for years but ....

Anyway, I'm pretty glad you're looking into this new bug and I still wish you a speedy recovery!

**Comment by TPetersen5171** [comment]
After resizing the mini map, it makes the quest icons on the mini map really larhe, went into mappy options clicked on smaller nodes, and it reduced the size for quest icons down to a more normal size, but changes them to what voxxel reported, maybe add a option to changed icon sizes if possible when you are feeling better

**Comment by Shushuda** [comment]
I'm not at the hospital, but I'm practically home bound. I have occipital neuralgia and regular treatment such as steroid nerve blocks make it worse instead of better. Other treatments, such as physical therapy, stretching and exercise, started helping a bit only very recently. The stretching and exercise part I was unable to do for half a year due to worsening of symptoms, but now I can do like 3 kinds of stretches without becoming worse, so progress I guess. I'm in Poland and I do everything privately because queues are horrible for the public health care.

Thank you for good wishes. Thankfully I didn't cancel the sub so I can always log in and do some debugging for the addon.

As for the resizing, if I remember correctly, both Blizzard's native option and addons use the same function - SetScale(). This enlarges everything as once - border, minimap bg, icons. Changing the icon size in Mappy is done by manually creating a texture map with smaller icons in Photoshop and replacing the in-game texture map with this addon one. I think I remember researching if this can be done dynamically and didn't find an answer. I think the Mappy's scale option still works the same as the one baked into Edit Mode, but I will recheck.

I will fix the textures this weekend, it should make the icons look normal with all Mappy options, sizes, blinking and whatnot. Keep in mind those are for gathering nodes only. Other icons will stay the same size. I could reduce them all, but that'd require quite a bit of manual editing in Photoshop. It is something doable tho.

**Comment by Voxxel** [comment]
I read after the occipital neuralgia and they say it could be very painful and long lasting. There are quite a lot patients who were able to ease the pain with intelligent neck massager devices, such like this: https://youtu.be/Mpo7K3P0Vls . You probably already tried it but wanted to share it with you either way. 

I'm looking forward for the new version with the fixed icon map so I can test it right off.

**Comment by Voxxel** [comment]
Hi there,
Any update on this?

**Comment by anathemamask** [comment]
Just adding that this is still, unfortunately, an issue. Any news on a forthcoming update would be very much appreciated - but i understand if it may not be coming soon.

**Comment by Shushuda** [comment]
Hey, sorry it took so long. I've uploaded the new release just now and will upload it to Curseforge in the next 30 minutes or so.

**Comment by Voxxel** [comment]
Hi Weronika! Thank you! I hope you're doing well.

**Comment by Voxxel** [comment]
I hope the next major patch 10.2 which is around the corner ( nov. 7) won't change the blip order once again. I'll try to test it on the PTR.

**Comment by Shushuda** [comment]
Oh it definitely will. Fixing the addon did make me want to set up WoW again and play, so I guess I will be fixing it a lot faster this time, hahah!

As for my health, I'll be honest - it's worse than it was. I don't know what to do, so might as well try to occupy myself with the new patch. Such is life.

**Comment by anathemamask** [comment]
I'll preface that i am by no means an experienced programmer, but if you'd like - at some point in the future if you walk me through your process for updating/fixing this issue, I could start submitting PRs to handle this for times when you're otherwise drowning in real life obligations.

**Comment by Shushuda** [comment]
Ah, the textures themselves are quite easy, it's purely Photoshop work. It's just time consuming and tedious. I really appreciate the offer! The 10.2 patch should be fine, I will be taking a 2 week PTO around the same time so I should be able to fix it much quicker this time.

Here's what I do to fix the textures, I use two programs for it + a graphic program to modify the textures (I have Photoshop so that's what I use):
1. Extract the current minimap blip texture with wow.export program. It's called ObjectIconsAtlas.blp.
2. Convert the texture from .blp to .png with BLPNG Converter program.
3. Modify the texture based on the ones that got outdated. There are a few texture files with very specific names (case sensitive) that are used by the addon, they all need to be replaced with updated ones - all based on that one single ObjectIconsAtlas. They're all possible option combinations for modifying those blip icons. I try to keep them pixel perfect, as in align them exactly the same.
4. After creating those new files, save them as .png into Artwork folder in the addon.
5. Use BLPNG Converter program to convert them all into .blp.
6. Put those .blp files into Textures folder in the addon.
7. Done.

The newest commit which replaces these textures should make this explanation a bit clearer.

As for Lua errors (so far so good but you never know), that's just Lua programming combined with traversing through Wowpedia to figure out Blizz-specific functions and whatnot.
