### ISSUE TITLE
Mappy and FarmHud integration

### ISSUE THREAD

**Issue by ItsmeGordo** [Shushuda/Mappy-Continued#13]
I'm trying to use Mappy and FarmHub at same time and something in bothering me.

After some time, apparently Mappy recognize that farming hub map is their map and move everything to the middle of FarmHub. The main problem in that Mappy change the size of map and things are showed in the same size of the minimap.

![{357180CF-4FED-44ED-BDEA-1D522AC9D691}](https://github.com/user-attachments/assets/08260d3d-3780-49a8-b92c-07bd8db2261c)

If you need some logs, teach me how to get it and I send here =)

**Comment by Shushuda** [comment]
Ooo, interesting one! I will take a look :D

**Comment by Shushuda** [comment]
Hmm, the FarmHud addon lists this in the description:

> Minimap / Nodes / FarmHud
> Blizzard has designed the Minimap element as All-in-One (Terrain texture + Nodes).
> It could not be separated. It could not be copied. Minimap and FarmHud can't be displayed at the same time.
> While mouseover is activated (Mouse on), the area for access to the 3D world is limited to the left and right on the screen boundaries.
> (It's like the Highlander: There can only be one.)

So it seems like they reuse the minimap frame for their layout and whatnot at the center since the texture cannot be separated. This might be why Mappy is trying to display icons at the center of the screen after a while, the frames might've moved there and it just went with it.

I'll verify in-game later, but I think that's the issue, they both try to access and modify the same frames. I will try to find some way to stop Mappy from interfering with Minimap size etc. when it detects FarmHud.

I'm currently awaiting surgery so I might have to pause the work on this when it comes up, but I will try my best to find some workaround.

**Comment by Shushuda** [comment]
@ItsmeGordo 
Could you go into "(...)\World of Warcraft\_retail_\WTF\Account\<your account num>\SavedVariables", open Mappy.lua, copy all text, upload it to a service such as pastebin.com and share the link with me? It's the config for Mappy.

Also could you do the same, but for FarmHud.lua (in the same folder as Mappy.lua)?

It will make reproducing this issue easier.

**Comment by Shushuda** [comment]
Hey, it's not needed after all hahah. I've fixed it.

Could you please test it before I upload it to Curseforge?

https://github.com/Shushuda/Mappy-Continued/releases/tag/4.6.7

**Comment by ItsmeGordo** [comment]
I'm gonna test it now. I send you a feedback in a hour or so

**Comment by ItsmeGordo** [comment]
Well... I tested here for around 15 minutes and it's looks like it's ok the integration. Things didn't move at all. I changed some settings, enabled/disabled farmhud sometimes to see if don't have a bug. I think you can ship it =D


![{46A7ED0E-60A6-4B81-A0D3-2A7491E66382}](https://github.com/user-attachments/assets/b3ff7545-c271-4c36-9ce0-6ed2b14b081e)

**Comment by Shushuda** [comment]
Ha, nice! Thanks :D
