### ISSUE TITLE
Console command

### ISSUE THREAD

**Issue by Voxxel** [Shushuda/Mappy-Continued#4]
/mappy lists a couple of console commands but I can't find the command that opens up the options.

I see it's in the game's own addon options but consider to make a standalone panel for it too because the stock options can't be moved from the center of the screen.

**Comment by Shushuda** [comment]
Ah, good catch, thanks.

I will add the redirect slash command to open the in-game options (under `/mappy`) and leave the help info under `/mappy help`. Although I remember that one of the recent beta builds broke that functionality even more (it was already broken, requiring 2 calls of the same function to open the options lmao). I need to check if it's also broken on retail.

As for the separate window, this will need some more writing since I've never done this before and I need to research how to create separate frames like that. I'm not sure if I will have the time for that, at least now, but I do see the appeal - it's modifying an existing UI element so moving the window out of view is useful. I will add this to my TODO, but I'm not sure when I will look at it.

**Comment by Shushuda** [comment]
The slash command part is done. It should appear on CurseForge after they approve it.
