### ISSUE TITLE
New patch 10.0.5 broke Mappy

### ISSUE THREAD

**Issue by Voxxel** [Shushuda/Mappy-Continued#7]
The minimap returned to the original round shape and /mappy doesn't do anything in the new patch. 

I got this error:

```
1x Mappy/Mappy.lua:35: table index is nil
[string "@Mappy/Mappy.lua"]:35: in main chunk

Locals:
```

**Comment by aledefreitas** [comment]
Solution is quite simple, just replace all occurrences of `MinimapCluster.MailFrame` with `MinimapCluster.IndicatorFrame`

**Comment by Shushuda** [comment]
Hi, thank you for the report @Voxxel and thank you for the solution @aledefreitas 

I will upload a new release today. Please let me know if there are any other issues, I'm not able to test it on my own. I'm currently battling a cervical issue that, tbf, ruined my whole life. I'm not very hopeful...

**Comment by Voxxel** [comment]
> 

Oh, dear, that sounds bad. :(  I hope there's nothing irreversible and you'll recover fast. I can only hope Poland has a better health care than Hungary... My fingers crossed for you.

**Comment by Shushuda** [comment]
I've been going exclusively to private doctors to deal with this as soon as possible to avoid permanent damage (I'd still be waiting for the first neurologist appointment if I went with public health care), but tbf, it's a lottery. All tests, MRIs, ultrasounds etc. show nothing wrong with me, just stiff tense neck and shoulder muscles, but I still have symptoms. I'm just throwing stuff at the wall and seeing if anything sticks. I'm supposed to do physiotherapy and exercises to relax and strengthen my neck, but after 3 weeks of going to sessions... I'm not sure if what I see is progress or just random changes. Doesn't help that some ppl recover after 4 days, while other ppl never, so I don't even know if it's working and how long to try. Tbh I could live with the pain and whatever, I only want one symptom to go away - severe debilitating tinnitus. The loud, unmaskable, multitone kind that cuts through all sounds and constantly fluctuates in volume and pitch. I really hope it's just the neck muscles being tense due to strain and it will stop once they stop pressing all the stuff around the spine and inner ear. It's torture.

The trigger for all those issues is almost funny. I wore a new heavy pair of headphones for a few days, without even playing sounds on them...
